"""initial schema with seven tables

Revision ID: 679ccd8cc0c2
Revises: 
Create Date: 2026-05-23 12:49:45.767386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '679ccd8cc0c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('environment_type', sa.Enum('ON_PREM_VM', 'AWS_EC2', 'AZURE_VM', 'KUBERNETES', name='environmenttype'), nullable=False),
    sa.Column('os_name', sa.String(length=100), nullable=False),
    sa.Column('os_eol_date', sa.Date(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('memory_gb', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('owner_team', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waves',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('wave_number', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('target_start_date', sa.Date(), nullable=False),
    sa.Column('target_end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('archetype', sa.Enum('LEGACY_MONOLITH', 'MODERN_MICROSERVICE', 'COTS_VENDOR', 'INTERNAL_TOOL', 'COMPLIANCE_CRITICAL', name='archetypetype'), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('runtime_version', sa.String(length=50), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'MISSION_CRITICAL', name='criticalitylevel'), nullable=False),
    sa.Column('owner_team', sa.String(length=100), nullable=False),
    sa.Column('app_owner_name', sa.String(length=100), nullable=False),
    sa.Column('infrastructure_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_id'], ['infrastructure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('source_app_id', sa.String(length=50), nullable=False),
    sa.Column('target_app_id', sa.String(length=50), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'MISSION_CRITICAL', name='criticalitylevel'), nullable=False),
    sa.ForeignKeyConstraint(['source_app_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['target_app_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operational_metrics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('incidents_last_quarter', sa.Integer(), nullable=False),
    sa.Column('mttr_hours', sa.Float(), nullable=False),
    sa.Column('availability_pct', sa.Float(), nullable=False),
    sa.Column('cpu_utilization_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('sixr_decision', sa.Enum('REHOST', 'REPLATFORM', 'REFACTOR', 'RETIRE', 'REPLACE', 'RETAIN', name='sixrdecision'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('dependency_warnings', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('wave_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['wave_id'], ['waves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_findings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('cve_id', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('discovered_date', sa.Date(), nullable=False),
    sa.Column('remediation_available', sa.Boolean(), nullable=False),
    sa.Column('remediation_steps', sa.Text(), nullable=True),
    sa.Column('mitigation_status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_findings')
    op.drop_table('recommendations')
    op.drop_table('operational_metrics')
    op.drop_table('dependencies')
    op.drop_table('applications')
    op.drop_table('waves')
    op.drop_table('infrastructure')
    # ### end Alembic commands ###
